import { useState } from 'react';
import { X, ChevronDown, ChevronUp } from 'lucide-react';

export interface HelpContent {
  title: string;
  description: string;
  steps: string[];
  faqs: { q: string; a: string }[];
}

export const HELP_CONTENT: Record<string, HelpContent> = {
  dashboard: {
    title: "Dashboard - Your Marketing Command Center",
    description: "Your central hub for monitoring all marketing activities. View AI agent activities, performance metrics, upcoming content, and growth opportunities in one unified view.",
    steps: [
      "Review the Agent Activity feed to see automated actions taken by VIMO",
      "Check the Morning Briefing for AI-generated insights and recommended actions",
      "Monitor performance snapshots and growth metrics at a glance",
      "Click on any card to dive deeper into specific areas"
    ],
    faqs: [
      { q: "Why is my dashboard empty?", a: "The dashboard populates as you create content and connect platforms. Start by setting up your brand profile and creating your first campaign in the Content Studio." },
      { q: "What are AI agents and how do they work?", a: "AI agents are specialized AI workers that automate marketing tasks. The Campaign Agent creates content, the Engagement Agent responds to comments, and the Analytics Agent monitors performance - all working 24/7 within your approval settings." },
      { q: "How often is the dashboard updated?", a: "Real-time updates occur for agent activities and scheduled posts. Performance metrics refresh every 6 hours from connected platforms." }
    ]
  },
  campaigns: {
    title: "Campaign Management - Strategic Marketing Runs",
    description: "Plan, execute, and manage comprehensive marketing campaigns across multiple platforms. Set goals, define timelines, and let AI generate a complete content strategy with scheduled posts.",
    steps: [
      "Click 'New Campaign' to launch the campaign wizard",
      "Define your campaign goal (product launch, follower growth, brand awareness, etc.)",
      "Set campaign duration, target platforms, and posting frequency",
      "Review the AI-generated content strategy and approve or edit posts",
      "Launch the campaign and monitor progress in real-time"
    ],
    faqs: [
      { q: "What happens after I create a campaign?", a: "VIMO's AI generates a complete content strategy including post ideas, captions, hashtags, and optimal posting times. You review and approve each piece of content before it gets scheduled." },
      { q: "Can I edit AI-generated campaign content?", a: "Yes, you have full control. Edit captions, change images, adjust posting times, or remove posts entirely before approving the campaign." },
      { q: "What does 'Awaiting Approval' status mean?", a: "Content has been generated by the AI but requires your review before it can be scheduled. This ensures quality control and maintains your brand voice." },
      { q: "Can I pause or modify an active campaign?", a: "Yes, you can pause campaigns at any time, edit upcoming posts, or extend/shorten the campaign duration as needed." }
    ]
  },
  content: {
    title: "Content Studio - AI-Powered Content Creation",
    description: "Create platform-optimized content with AI assistance. Generate posts, scripts, hashtags, and visual suggestions. Create A/B test variants, repurpose content across platforms, and access the AI Designer for visual content.",
    steps: [
      "Select your brand profile and target platform from the dropdowns",
      "Enter your content topic or main message",
      "Add additional context like specific details, links, or requirements",
      "Click 'Generate' to create AI-optimized content with hashtags and image suggestions",
      "Use 'Create Variants' for A/B testing or 'Repurpose' to adapt for other platforms"
    ],
    faqs: [
      { q: "How does the AI generate content?", a: "VIMO analyzes your brand profile, target platform best practices, trending topics, and your input to generate optimized content with engaging hooks, relevant hashtags, and visual suggestions." },
      { q: "What are content variants and how do they work?", a: "Variants are different versions of the same content idea with varying tones, lengths, or angles. Use them for A/B testing to see what resonates best with your audience." },
      { q: "How does the 'Additional Context' field help?", a: "Adding context like specific facts, URLs, target audience details, or content requirements helps the AI generate more accurate and relevant content tailored to your needs." },
      { q: "Can I edit AI-generated content before posting?", a: "Absolutely. All generated content is fully editable. You can modify captions, swap hashtags, change image suggestions, or rewrite entirely before scheduling." },
      { q: "What platforms are supported for content generation?", a: "VIMO supports Instagram, LinkedIn, X (Twitter), TikTok, YouTube, Facebook, Pinterest, Reddit, Bluesky, and Threads with platform-specific optimization for each." }
    ]
  },
  connectors: {
    title: "Connector Hub - Platform Integrations",
    description: "Connect VIMO to your AI providers and social media platforms. Manage connections, API keys, and authentication for all integrated services in one central location.",
    steps: [
      "Browse available connectors organized by category (AI Providers, Social, Analytics)",
      "Click 'Connect' on any provider to start the authentication process",
      "For connected providers (Instagram, LinkedIn, etc.), simply click 'Allow' in the popup",
      "For API key providers (OpenAI, Anthropic), paste your key and click 'Save'",
      "Test the connection to verify everything is working properly"
    ],
    faqs: [
      { q: "How does connecting work?", a: "For supported platforms like Instagram, LinkedIn, and Canva, simply click 'Connect' and authorize VIMO in the popup window. No need to copy/paste tokens - we handle the entire connection flow automatically and store tokens securely." },
      { q: "Where do I find API keys for AI providers?", a: "OpenAI: platform.openai.com/api-keys | Anthropic: console.anthropic.com | Groq: console.groq.com/keys | Google: aistudio.google.com/app/apikey" },
      { q: "Is my connection data secure?", a: "Yes. All API keys and connection tokens are encrypted using AES-256 before being stored in your local database. VIMO never sends your credentials to external servers." },
      { q: "Why is my connector showing 'error' status?", a: "This usually means the API key is invalid or expired, or the connection token needs refreshing. Try re-authenticating or check your credentials." },
      { q: "Can I connect multiple accounts of the same platform?", a: "Yes. You can connect multiple Instagram accounts, LinkedIn profiles, or other platforms. Each will show as a separate connector with its own credentials." }
    ]
  },
  settings: {
    title: "Settings",
    description: "Configure your app-wide preferences, security, and data management.",
    steps: [
      "Set your default brand and timezone in General settings.",
      "Assign specific AI models to different tasks in AI Model settings.",
      "Export or reset your data in the Data & Privacy tab."
    ],
    faqs: [
      { q: "How do I change my PIN?", a: "Go to General settings and look for the 'Change PIN' section." },
      { q: "Can I export my data?", a: "Yes, you can download a full JSON dump of your data from the Privacy tab." }
    ]
  },
  scheduler: {
    title: "Content Scheduler",
    description: "Plan and manage all your scheduled posts in one calendar view. See what is going live and when.",
    steps: [
      "Browse the monthly calendar to see all scheduled posts at a glance.",
      "Click on a date to view or edit posts scheduled for that day.",
      "Use the 'New Post' button to create and schedule content directly."
    ],
    faqs: [
      { q: "How do I reschedule a post?", a: "Click on the date with the post you want to reschedule, then use the Edit button to change its time." },
      { q: "What do the colored dots mean?", a: "Each colored dot represents a scheduled post. The color corresponds to the platform (pink for Instagram, blue for LinkedIn, etc.)." },
      { q: "Can I cancel a scheduled post?", a: "Yes, select the post in the day panel and click the Cancel button. The post will be removed from the schedule." }
    ]
  },
  viral: {
    title: "Viral Studio",
    description: "Turn long-form videos into short-form clips optimized for TikTok, Instagram Reels, and YouTube Shorts.",
    steps: [
      "Select a brand profile to associate with your video.",
      "Upload an .mp4, .mov, or .webm video file (up to 2GB).",
      "Wait for VIMO to transcribe, detect viral moments, and extract clips automatically.",
      "Download clips or schedule them directly to your social platforms."
    ],
    faqs: [
      { q: "What kind of videos work best?", a: "Videos with clear speaking, varied delivery, and natural pauses work best. Talking head and educational content typically generates the best clips." },
      { q: "How does the virality score work?", a: "The AI analyzes your video for emotional peaks, surprising moments, and engaging hooks. Higher scores (80+) indicate moments most likely to perform well as standalone clips." },
      { q: "Can I edit the clips after extraction?", a: "Yes, you can download any clip and edit it further. The 'Schedule this clip' button lets you create a post with the clip attached." }
    ]
  },
  engagement: {
    title: "Engagement Queue",
    description: "Manage your social media comments and interactions in one place. VIMO detects intent, suggests replies, and helps you respond faster.",
    steps: [
      "Connect your social accounts in the Connector Hub to start receiving comments.",
      "Review the queue — high-priority purchase enquiries appear at the top.",
      "Use 'Generate AI Reply' to get a suggested response, then reply or edit before sending.",
      "Use 'Sync now' to pull the latest comments from your connected platforms."
    ],
    faqs: [
      { q: "How does VIMO detect purchase intent?", a: "VIMO analyzes comment content using AI intent classification. Comments with purchase intent are flagged with a 'Potential sale' badge and appear as high priority." },
      { q: "Can VIMO reply automatically?", a: "Yes, VIMO can auto-reply to low-risk comments. High-priority items (purchase enquiries, complaints) are flagged for your review before any reply is sent." },
      { q: "What do the sentiment badges mean?", a: "VIMO classifies each comment as Positive, Negative, or Neutral. Spam comments are detected and filtered automatically." }
    ]
  },
  analytics: {
    title: "Analytics Dashboard",
    description: "Track your marketing performance across all platforms with reach, engagement, and trend data.",
    steps: [
      "Select a brand profile and date range to see your performance metrics.",
      "Review the 'Your week at a glance' brief for an AI-generated summary.",
      "Open 'What worked this week' to see your top-performing posts.",
      "Use the Marketing Time Machine to ask questions about your growth."
    ],
    faqs: [
      { q: "Where does the data come from?", a: "Performance data is collected from your connected social platforms. Reach and engagement metrics are updated every 6 hours." },
      { q: "What is Marketing Time Machine?", a: "It is an AI feature that answers questions about your growth trends in plain English. Ask questions like 'Why did engagement drop?' and get a story-based analysis." },
      { q: "How are recommendations generated?", a: "VIMO analyzes your posting patterns, engagement data, and industry benchmarks to suggest the best times, content types, and growth actions for the upcoming week." }
    ]
  },
  autopilot: {
    title: "One-Click Autopilot - Fully Automated Marketing",
    description: "Launch complete marketing campaigns with a single click. Enter your goal and audience, and VIMO handles research, strategy creation, content generation, scheduling, and execution - all fully autonomous.",
    steps: [
      "Select your brand profile and campaign goal (grow followers, product launch, drive traffic, etc.)",
      "Describe your target audience and any specific requirements",
      "Choose campaign duration (2-8 weeks) and select target platforms",
      "Review the AI-generated strategy and click 'Launch Autopilot'",
      "Monitor progress in real-time as VIMO creates and schedules all content automatically"
    ],
    faqs: [
      { q: "What does Autopilot actually do?", a: "Autopilot is VIMO's fully automated marketing system. Once launched, it researches trends, analyzes your brand, creates a complete content strategy, writes all posts, schedules them at optimal times, and can even respond to comments - all without further input from you." },
      { q: "Can I review content before it goes live?", a: "Yes, depending on your approval mode. In 'Safe' mode, everything waits for your approval. In 'Assisted' mode (default), posts wait for approval but engagement is auto-approved. In 'Autonomous' mode, everything runs without your intervention." },
      { q: "How long should I run an Autopilot campaign?", a: "For best results, we recommend 4-6 week campaigns. This gives the AI enough time to test different content types, learn from performance data, and optimize the strategy. Shorter 2-week campaigns work for product launches or events." },
      { q: "Can I pause or stop an Autopilot campaign?", a: "Yes, you can pause, resume, or stop any Autopilot campaign at any time. Paused campaigns retain their schedule and can be resumed later. Stopped campaigns are archived and can be reviewed for learning." }
    ]
  },
  brandmemory: {
    title: "Brand Memory - Your Marketing Knowledge Base",
    description: "Access your complete marketing history including performance lessons, audience insights, campaign records, and evolving Content DNA. VIMO learns from every post to make smarter recommendations over time.",
    steps: [
      "Review Performance Lessons to see what's worked and what hasn't",
      "Explore Audience Insights to understand your engaged segments",
      "Check Campaign Memory for complete records of past campaigns",
      "View Content DNA to see your evolving brand voice and top-performing hooks"
    ],
    faqs: [
      { q: "What is Content DNA?", a: "Content DNA is VIMO's understanding of your brand's unique voice and what works for your audience. It includes your strongest hooks, topics to avoid, best-performing content types, and how your voice has evolved over time." },
      { q: "How are Performance Lessons created?", a: "After each post is published, VIMO analyzes its performance and extracts specific lessons about what worked (e.g., 'List-style captions performed 40% better'). These become part of your Brand Memory." },
      { q: "What are Audience Insights?", a: "As VIMO analyzes your engagement data, it discovers segments of your audience (e.g., 'Young professionals interested in productivity'). For each segment, it tracks what content they engage with and the best times to reach them." },
      { q: "Does VIMO really learn over time?", a: "Yes. Every post, campaign, and engagement helps VIMO understand what works for your brand. The Marketing Director uses this memory to make increasingly accurate recommendations as time goes on." }
    ]
  },
  intelligence: {
    title: "Marketing Intelligence - Insights & Analytics",
    description: "Access deep marketing insights including the Marketing Time Machine for historical analysis, performance trends, competitor intelligence, and AI-generated recommendations for growth.",
    steps: [
      "Use the Marketing Time Machine to ask questions about your historical data",
      "Review performance trends and identify patterns in your growth",
      "Explore competitor intelligence and market positioning insights",
      "Review AI-generated recommendations for your next growth actions"
    ],
    faqs: [
      { q: "What is the Marketing Time Machine?", a: "The Time Machine is an AI feature that analyzes up to 12 weeks of your marketing data to answer questions in plain English. Ask things like 'Why did engagement drop last month?' and get a narrative answer with root cause analysis." },
      { q: "How does competitor intelligence work?", a: "VIMO can analyze publicly available data about your competitors' content strategies, posting frequencies, and engagement patterns. This helps identify gaps and opportunities for your own strategy." },
      { q: "What kind of recommendations does VIMO provide?", a: "Recommendations include optimal posting times, content types to focus on, hashtag strategies, platform prioritization, and specific growth actions based on your current performance data." },
      { q: "How often is intelligence data updated?", a: "Your own performance data updates every 6 hours from connected platforms. AI insights and recommendations refresh daily, while the Marketing Director can be run on-demand for real-time analysis." }
    ]
  },
  approvals: {
    title: "Approval Queue - Content Review & Control",
    description: "Review and approve all AI-generated content before it goes live. Manage posts, engagement replies, and campaign actions based on your approval mode settings.",
    steps: [
      "Review pending items in your approval queue",
      "Check urgency indicators and batch similar items together",
      "Approve, reject, or edit each item before it executes",
      "Use batch controls to approve multiple items at once"
    ],
    faqs: [
      { q: "What are approval modes?", a: "VIMO has three approval modes: 'Safe' (everything requires approval), 'Assisted' (posts require approval, engagement auto-approved if high confidence), and 'Autonomous' (everything runs automatically within your rules)." },
      { q: "What types of items appear in the approval queue?", a: "Posts ready to be published, engagement replies, campaign actions, scheduled content, and any other action that touches external platforms based on your approval mode." },
      { q: "Can I batch approve items?", a: "Yes. You can approve all items of a specific type, all items from a particular campaign, or use the 'Approve All' button for low-risk items (if your approval mode allows)." },
      { q: "What happens if I reject an item?", a: "Rejected items are moved to an archive and can be reviewed later. If it was a post, you'll need to create a new one. If it was an engagement reply, VIMO will not respond to that comment." }
    ]
  },
  'connector-hub': {
    title: "Pack Marketplace - Power-Up Your Marketing",
    description: "Install powerful connector packs to give VIMO access to your tools and data. Each pack unlocks new content capabilities by connecting your Shopify store, GitHub repos, Stripe payments, Slack workspace, and more.",
    steps: [
      "Browse packs by category — Knowledge Packs, Intelligence Packs, and Creative Commerce",
      "Click on a pack to view details, capabilities, and setup instructions",
      "Click 'Connect' to start the guided setup flow",
      "For API-key-based packs (Shopify, Stripe), follow the in-app instructions to generate and paste credentials",
      "For connected packs (GitHub, Canva), authorize via the secure popup window",
      "After connecting, the discovery step shows real data from your account"
    ],
    faqs: [
      { q: "What's the difference between pack types?", a: "Knowledge Packs give VIMO context from your tools (GitHub, Notion, Slack). Intelligence Packs provide market insights (competitor tracking, SEO). Creative Commerce packs let VIMO access your products for promotional content (Shopify, Canva)." },
      { q: "How do I remove a pack?", a: "Open the Installed Packs section and click the 'Remove' button on any pack. This will disconnect VIMO from that service and remove its data from your workspace." },
      { q: "Can I reconnect a pack after removing it?", a: "Yes, packs can be reconnected at any time by clicking 'Connect' again. Your previous settings and credentials will not be retained after removal." },
      { q: "What if my credentials are wrong?", a: "Don't worry — if a credential is invalid, the pack will show an error status. You can click 'Remove' and reconnect with the correct credentials at any time." },
      { q: "Do I need to configure credentials myself?", a: "For some packs (GitHub, Canva, Notion), VIMO provides built-in connections — just click allow. For others, the guided setup walks you through creating credentials step by step, with copyable redirect URLs." },
    ]
  },
  'social-accounts': {
    title: "Social Accounts - Manage Your Platforms",
    description: "Connect and manage your social media platforms — Instagram, Facebook, LinkedIn, X (Twitter), TikTok, YouTube, Pinterest, Threads, and Bluesky. Control permissions and select which accounts VIMO can manage.",
    steps: [
      "Click 'Connect' on any platform to start the connection flow",
      "For Instagram and Facebook, authorize via Meta's secure popup",
      "For LinkedIn, grant the required permissions for posting",
      "After connecting, review and select which accounts VIMO can access",
      "Toggle permissions and manage connections from the platform list"
    ],
    faqs: [
      { q: "Why do I need to connect social accounts individually?", a: "Each platform requires separate authorization for security. VIMO uses official connection flows so you stay in control of what data and publishing permissions you grant." },
      { q: "Can VIMO post to my accounts automatically?", a: "Yes, with your permission. VIMO can schedule and publish content to connected accounts based on campaigns and autopilot runs. You control this through Approval Mode settings." },
      { q: "What permissions does VIMO request?", a: "VIMO requests read access to see your profile and content, and write access to publish posts on your behalf. Specific permissions vary by platform and are shown during the connection flow." },
      { q: "How do I disconnect a platform?", a: "Go to Social Accounts, find the platform, and click 'Disconnect'. This revokes VIMO's access and removes the stored tokens." },
    ]
  },
  brandroast: {
    title: "Brand Roast - Honest Marketing Analysis",
    description: "Get a brutally honest analysis of your entire marketing strategy. VIMO analyzes your brand profile, recent posts, campaign history, and competitor data to score your marketing and provide specific, actionable fixes.",
    steps: [
      "Select the brand profile you want analyzed",
      "Choose analysis depth (Quick Scan or Deep Roast)",
      "Review VIMO's findings across positioning, messaging, content, and competitors",
      "Access your actionable fix list prioritized by impact",
      "Share your roast score (optional - designed to go viral)"
    ],
    faqs: [
      { q: "What does the Brand Roast analyze?", a: "The roast examines your brand positioning, messaging consistency, content quality and variety, posting patterns, engagement rates, competitor positioning, website content, and overall marketing strategy - then scores each area out of 100." },
      { q: "How is the overall roast score calculated?", a: "Your total score (0-100) is a weighted average across positioning (20%), messaging (20%), content (25%), consistency (15%), and competitive position (20%). A score above 75 is considered strong." },
      { q: "Are the fixes really actionable?", a: "Yes. Unlike generic advice, each fix is specific to your brand. Instead of 'post more consistently,' you'll get 'Post 3x weekly on Tuesday/Thursday at 9am when your audience is most active, focusing on educational carousels which outperform your other content by 40%.'" },
      { q: "Can I run a roast for a competitor?", a: "Yes. You can create a brand profile for any public brand and run a roast analysis. This is useful for competitive intelligence and understanding where you stand in your market." }
    ]
  }
};

interface Props {
  isOpen: boolean;
  onClose: () => void;
  pageId: string;
}

export default function HelpPanel({ isOpen, onClose, pageId }: Props) {
  const content = HELP_CONTENT[pageId] || HELP_CONTENT.dashboard;
  const [expandedFaq, setExpandedFaq] = useState<number | null>(null);

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 overflow-hidden">
      <div className="absolute inset-0 bg-slate-900/20 backdrop-blur-sm" onClick={onClose} />
      <div className="absolute inset-y-0 right-0 w-full max-w-md bg-white shadow-2xl dark:bg-slate-900">
        <div className="flex h-full flex-col">
          <div className="flex items-center justify-between border-b border-slate-100 p-6 dark:border-slate-800">
            <div>
              <h2 className="text-xl font-bold text-slate-900 dark:text-white">VIMO Help Center</h2>
              <p className="text-xs text-slate-500">How to get the most out of your AI agency</p>
            </div>
            <button onClick={onClose} className="rounded-lg p-2 text-slate-400 hover:bg-slate-50 dark:hover:bg-slate-800">
              <X className="h-5 w-5" />
            </button>
          </div>

          <div className="flex-1 overflow-y-auto p-6 space-y-8">
            <section className="space-y-3">
              <h3 className="text-lg font-bold text-teal-600 dark:text-teal-400">{content.title}</h3>
              <p className="text-sm leading-relaxed text-slate-600 dark:text-slate-400">{content.description}</p>
            </section>

            <section className="space-y-4">
              <h4 className="text-xs font-bold uppercase tracking-wider text-slate-400">Next Steps</h4>
              <div className="space-y-4">
                {content.steps.map((step, i) => (
                  <div key={i} className="flex space-x-3">
                    <span className="flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-teal-50 text-xs font-bold text-teal-600 dark:bg-teal-900/30 dark:text-teal-400">
                      {i + 1}
                    </span>
                    <p className="text-sm text-slate-700 dark:text-slate-300">{step}</p>
                  </div>
                ))}
              </div>
            </section>

            <section className="space-y-4">
              <h4 className="text-xs font-bold uppercase tracking-wider text-slate-400">Common Questions</h4>
              <div className="divide-y divide-slate-100 rounded-xl border border-slate-100 dark:divide-slate-800 dark:border-slate-800">
                {content.faqs.map((faq, i) => (
                  <div key={i} className="overflow-hidden">
                    <button
                      onClick={() => setExpandedFaq(expandedFaq === i ? null : i)}
                      className="flex w-full items-center justify-between p-4 text-left hover:bg-slate-50 dark:hover:bg-slate-800/50"
                    >
                      <span className="text-sm font-medium text-slate-900 dark:text-white">{faq.q}</span>
                      {expandedFaq === i ? <ChevronUp className="h-4 w-4 text-slate-400" /> : <ChevronDown className="h-4 w-4 text-slate-400" />}
                    </button>
                    {expandedFaq === i && (
                      <div className="bg-slate-50 p-4 pt-0 dark:bg-slate-800/30">
                        <p className="text-xs leading-relaxed text-slate-600 dark:text-slate-400">{faq.a}</p>
                      </div>
                    )}
                  </div>
                ))}
              </div>
            </section>
          </div>

          <div className="border-t border-slate-100 p-6 dark:border-slate-800">
            <a
              href="https://github.com/yourusername/vimo/discussions"
              target="_blank"
              rel="noopener noreferrer"
              className="flex w-full items-center justify-center space-x-2 rounded-xl bg-slate-900 py-3 text-sm font-bold text-white hover:bg-slate-800 dark:bg-teal-600 dark:hover:bg-teal-700"
            >
              <span>GitHub Discussions</span>
            </a>
          </div>
        </div>
      </div>
    </div>
  );
}
