import React from 'react';
import {
  AlertCircle,
  BarChart3,
  Bell,
  BookOpen,
  Brain,
  Calendar,
  CheckCircle2,
  Circle,
  CircleDot,
  ClipboardList,
  CreditCard,
  DollarSign,
  Eye,
  Files,
  FileText,
  FolderOpen,
  GitCommit,
  Github,
  Globe,
  Heart,
  Image,
  Instagram,
  Kanban,
  Layers,
  Lightbulb,
  ListChecks,
  Mail,
  Megaphone,
  MessageCircle,
  MessageSquare,
  Package,
  Palette,
  PenTool,
  Radar,
  RefreshCw,
  Search,
  ShoppingBag,
  ShoppingCart,
  Speaker,
  Star,
  Table,
  Tag,
  Target,
  TrendingUp,
  Type,
  Users,
  Zap,
} from 'lucide-react';

// Explicit allowlist — every `icon:` string used by pack definitions and the
// backend discovery service. Named imports (NOT `import *`) so bundlers can
// tree-shake lucide: the namespace import pulled the entire icon library
// (~800KB) into the ConnectorHub chunk. Unknown names fall back to Circle,
// so adding a new pack icon only ever needs one line here.
const ICONS: Record<string, React.ElementType> = {
  AlertCircle,
  BarChart3,
  Bell,
  BookOpen,
  Brain,
  Calendar,
  CheckCircle2,
  Circle,
  CircleDot,
  ClipboardList,
  CreditCard,
  DollarSign,
  Eye,
  Files,
  FileText,
  FolderOpen,
  GitCommit,
  Github,
  Globe,
  Heart,
  Image,
  Instagram,
  Kanban,
  Layers,
  Lightbulb,
  ListChecks,
  Mail,
  Megaphone,
  MessageCircle,
  MessageSquare,
  Package,
  Palette,
  PenTool,
  Radar,
  RefreshCw,
  Search,
  ShoppingBag,
  ShoppingCart,
  Speaker,
  Star,
  Table,
  Tag,
  Target,
  TrendingUp,
  Type,
  Users,
  Zap,
};

export function resolveIcon(iconName: string): React.ElementType {
  return ICONS[iconName] || Circle;
}
